### ISSUE TITLE
overline use multicore and regionalisation

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#101]
The defaults for `stplanr::overline` are `ncores = 1` and `regionalise = 1e9` which slow down the build

Would be good to set a lower regionalise e.g. `1e6` and detect/set multiple cores support e.g. `parallelly::availableCores`

I guess other parts may benefit from multicore support.

**Comment by Robinlovelace** [comment]
Sounds good, PR welcome to implement this. Would be good to benchmark this.

**Comment by Robinlovelace** [comment]
I don't see this as a priority. We can allow the computer to do the hard work and chug away on the data, only requiring update frequency once per month. Closing for now as a 'wontfix' but happy to discuss, I think this issue may be best located in the `stplanr` issue tracker.

**Comment by Robinlovelace** [comment]
Also if performance is important we can switch to the Rust implementation at some point, in the same way that we switched to Rust for the jittering: https://github.com/acteng/overline
