### ISSUE TITLE
Quietest network stops and starts

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#125]
As shown below, for example:

![image](https://github.com/nptscot/npt/assets/1825120/428079d7-e9c6-427b-9596-5b8877a045f9)

Source:

**Comment by Robinlovelace** [comment]
https://nptscot.github.io/#14.01/56.45668/-3.01273

**Comment by Robinlovelace** [comment]
Issue identified with total:

![image](https://github.com/nptscot/npt/assets/1825120/ad956875-f4de-418e-ab56-8d03b25eba93)

**Comment by Robinlovelace** [comment]
Will close when fix is on production @mem48

**Comment by Robinlovelace** [comment]
Now fixed on dev version:

![image](https://github.com/nptscot/npt/assets/1825120/47527287-ca0f-42f4-81e2-65424af31c90)

Source: https://nptscot.github.io/#16.08/56.454546/-3.011159

Can we get this on production ASAP @mem48 ?

**Comment by mem48** [comment]
The schools' network doesn't look ready for production, lots of missign data?

**Comment by Robinlovelace** [comment]
> The schools' network doesn't look ready for production, lots of missing data?

Where? We need examples, with reference to the data on the test version and with reference to the data you produced @mem48 in this issue: https://github.com/nptscot/npt/issues/152

**Comment by mem48** [comment]
As discussed no data in Falkirk https://nptscot.github.io/#11.33/56.0031/-3.7975

**Comment by Robinlovelace** [comment]
Agreed. Should be fixed by #157, eventually...

**Comment by Robinlovelace** [comment]
This is now fixed.
