### ISSUE TITLE
Add fastest and quietest route networks

### ISSUE THREAD

**Issue by atumscott** [nptscot/npt#13]
We should add additional route types.

@mem48 has already added the option to the UI, now we just need the data!

Happy to give this one a bash...

**Comment by Robinlovelace** [comment]
Update here: currently it's generating 34k routes with `min_flow = 10`:

https://github.com/nptscot/npt/blob/76d1da7e7b2d0ed612e8b8a5241376488384e58d/_targets.R#L36
