### ISSUE TITLE
Missing canal tow path

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#138]
Feedback from workshop

https://www.cyclestreets.net/journey/89882807/#quietest

**Comment by Robinlovelace** [comment]
I guess this is due to data issues in OSM, and we can fix upstream. Thoughts @mvl22?

**Comment by Robinlovelace** [comment]
OK, this is missing on the web app? Duplicate of #66 I think.

**Comment by Robinlovelace** [comment]
Duplicate of this sorry: https://github.com/nptscot/npt/issues/125

**Comment by mvl22** [comment]
Can you clarify the problem?

The router has chosen the west side of the canal probably because that is marked as asphalt tracktype=1 [i.e. smooth] rather than cobblestone ['loose rounded medium sized stones'].

If I had to go that distance, based on that data I'd probably do the same.

**Comment by Robinlovelace** [comment]
Duplicate of https://github.com/nptscot/npt/issues/125 as I said above. Will re-open that and close this one to reduce confusion.

**Comment by mem48** [comment]
@mvl22 Not sure there is any problem. I just wanted to note some feedback from a workshop with local planners, for futher investigation. I think @Robinlovelace has got the wrong end of the stick.

**Comment by Robinlovelace** [comment]
@mem48 what was the feedback?

**Comment by Robinlovelace** [comment]
@mem48 OK I see now, it's feedback for CycleStreets like #66. The explanation above is reasonable @mvl22, I would probably do the same. On a different but related note, have you looked into this feedback I provided a while back? There were too many turns in all the routes last time I checked: https://github.com/cyclestreets/cyclestreets-setup/issues/34

**Comment by mvl22** [comment]
> On a different but related note, have you looked into this feedback I provided a while back?

Yes, I'll add another reply.
