### ISSUE TITLE
Project management tasks

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#139]
- [x] Scenario definitions @mem48 and tracked in https://github.com/nptscot/npt/issues/27
- [x] Update Phase 2/3 with maintenance info and cost estimates
- [x] Description of Phase 1 other trip purposes #35 (paper on non commute trip modelling)
- [x] Update Gantt with update on resource spend so far with Dec end
- [x] Updates on data provision

**Comment by Mattpdavis** [comment]
I don't seem to be able to edit the list above so my revisions:

- Description of Phase 1 other trip purposes (share methodology paper with Angus & Matt)
- Update Phase 2/3 with cost estimates (can be cost ranges)
- updates on data provision (chase up HUSS data from Sustrans, confirm when higher res Census commute data received)
-

**Comment by Robinlovelace** [comment]
Closing for now. The first task is not fully done but we're on the case and the scenarios task is tracked here https://github.com/nptscot/npt/issues/27 so closing as this issue is superseded by that.
