### ISSUE TITLE
Overline that retains OSM ID

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#17]
Idea: A version of overline thas can pass through non-numerical data

**Comment by Robinlovelace** [comment]
Fully agreed, great idea. I plan to open an issue in `stplanr` although I suspect that starting from scratch may be the best plan.

**Comment by Robinlovelace** [comment]
I found the `rnet_join()` function, already in `stplanr`! https://github.com/ropensci/stplanr/issues/509

**Comment by Robinlovelace** [comment]
And: https://github.com/ropensci/stplanr/issues/458
