### ISSUE TITLE
Error with overline function

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#184]
I'm getting this issue in the rnet_commute_list target

```
  Last error: error writing to connection
```

Looking online it does not seem that common but possibly caused by parallel processing: https://www.google.com/search?client=firefox-b-d&q=error+writing+to+connection+R

Thoughts @mem48?

**Comment by mem48** [comment]
Connection errors usually mean writing to a file, possibly it is missing or write protected.

**Comment by Robinlovelace** [comment]
Traceback has the answer I think...

<html>
<body>
<pre tabindex="0" aria-label="Console Output" role="document" class="GNVWDDMDJ3B" id="rstudio_console_output" style="font-family: &quot;Lucida Console&quot;, monospace; font-size: 13.3333px; outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; line-height: 1.2; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span tabindex="-1" class="GNVWDDMDK3B" role="document" style="outline: none;"><div class="GNVWDDMDEID ace_console_error" style="position: relative; overflow: hidden; margin: 5px 5px 5px 0px; padding: 5px 0px 5px 10px; white-space: pre-line; background-color: rgb(230, 230, 230);"><div class="GNVWDDMDIID GNVWDDMDD3B  ace_constant" style="display: inline; overflow-wrap: break-word; word-break: break-word; color: rgb(197, 6, 11);"><span>Error in serialize(data, node$con) : error writing to connection</span></div><div class="GNVWDDMDJID stack_trace" aria-hidden="true" style="margin-top: 0.5em; margin-left: 0.3em; display: block;">

12. | serialize(data, node$con)
-- | --


</div></div><span class="GNVWDDMDJ3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;"></span></pre><br class="Apple-interchange-newline">
</body>
</html>

**Comment by Robinlovelace** [comment]
```
Error in serialize(data, node$con) : error writing to connection
12.
serialize(data, node$con)
11.
sendData.SOCKnode(con, list(type = type, data = value, tag = tag))
10.
sendData(con, list(type = type, data = value, tag = tag))
9.
postNode(con, "EXEC", list(fun = fun, args = args, return = return,
                           tag = tag))
8.
sendCall(cl[[i]], fun, argfun(start + i - 1L))
7.
staticClusterApply(cl, fun, length(x), argfun)
6.
clusterApply(cl = cl, x = splitList(X, nchunks), fun = lapply,
             FUN = fun, ...)
5.
do.call(c, clusterApply(cl = cl, x = splitList(X, nchunks), fun = lapply,
                        FUN = fun, ...), quote = TRUE)
4.
PAR_FUN(cl, X[Split[[i]]], FUN, ...)
3.
pbapply::pblapply(sl, function(y) {
    y <- dplyr::group_by_at(y, attrib)
    y <- dplyr::summarise(y, do_union = FALSE, .groups = "drop")
}, cl = cl)
2.
stplanr::overline2(r, attrib = c("bicycle", "bicycle_go_dutch",
                                 "Quietness", "Gradient"), fun = list(sum = sum, max = first),
                   ncores = ncores, regionalise = regionalise) at <text>#14
    1.
make_rnets(uptake_list_commute[[p]], ncores = 20)

```

**Comment by Robinlovelace** [comment]
I still think it's about the number of cores...

**Comment by Robinlovelace** [comment]
Yep:

```
parallel::detectCores()
[1] 8
```

Maybe next time set it to `detectCores()` cores. Also have you done any recent benchmarks showing speed-up with more cores? As far as I recall adding more cores doesn't lead to a substantial speed-up with `overline()` but happy to be proved wrong on that..
