### ISSUE TITLE
Update schools network with new hands-up data

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#189]
This will involve adding new data for 4 authorities. @mem48's on the case today!

**Comment by Robinlovelace** [comment]
Is this now done @mem48 ? Please close when it is.

**Comment by mem48** [comment]
Jittering is still running, don't know if it has crashed.

Should just be source this file https://github.com/nptscot/npt/blob/main/code/prep_school_data.R

**Comment by mem48** [comment]
@Robinlovelace is now done, by turning off deduplication in od_jitter. New file in Teams folder

**Comment by Robinlovelace** [comment]
:tada:

**Comment by mem48** [comment]
NB still missing some HOS data, but at least we have more than before. Default mode share is assumed when data is missing.
