### ISSUE TITLE
Standard mode splits

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#191]
Commute and Schools data split modes differently, and differently from the split in the PCT

**Commute data**

1 | Work or study mainly at home
2 | Train
3 | Underground, subway, metro, light rail or tram
4 | Bus, mini-bus, coach
5 | Driving or a passenger in a car or van
6 | Bicycle
7 | Foot
8 | Taxi or motorcycle
9 | No fixed workplace

**Schools Data**

Walk | Cycle | Scooter / Skate | Park & Stride | Driven | Bus | Taxi | Other

Would help to have a standard way to divide modes

**Comment by Robinlovelace** [comment]
This is really interesting Malcolm. Bicycle - Cycle is enough for now, right?

**Comment by mem48** [comment]
I'm going to suggest we go for:

Walk, Cycle, Public Transport, Car, Taxi, Other

As the modes in the tool. With the rules

Scooter / Skate = walk
Park & Stride = car

**Comment by Robinlovelace** [comment]
Sounds reasonable to me for now.
