### ISSUE TITLE
Not enough workplace subpoints

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#196]
When we used Intermediate Zones, the subpoints for jittering were the centroids of the workplace zones.

Now we have switched to smaller Data Zones there are not enough subpoints. In my current build, I'm using the OA centroids as subpoints for origin and destination. which works but is not ideal because we are routing to residential areas rather than workplaces.

As an alternative option, I'm thinking of using the OS points of interest https://www.ordnancesurvey.co.uk/products/points-of-interest which is free on Digimap, but we would have to treat it as secure data

The POI cover:

-         Accommodation
-         Eating and drinking
-         Commercial services
-         Attractions
-         Sport and entertainment
-         Education and health
-         Public infrastructure
-         Manufacturing and production
-         Retail
-         Transport

Which sounds to me like a good proxy for workplaces. But does miss out offices and some types of workplaces. 

Flagging to @joeytalbot as this may be relevant to your work on other journey purposes and @Robinlovelace for an overall steer on this.

**Comment by Robinlovelace** [comment]
These sound really good subpoints for destinations. Thoughts on origins?

**Comment by mem48** [comment]
Screenshot of the POI data 

![image](https://github.com/nptscot/npt/assets/15819577/9ba4b685-32b8-4ac5-a099-2c02af657a89)

For origins, we can still use the OA centroids as roughly 5 per Data Zone

![image](https://github.com/nptscot/npt/assets/15819577/3feca59e-36e9-4041-8618-e6adf3778f9b)

**Comment by Robinlovelace** [comment]
Sounds good, although wasn't there at least 1 where there were no origin subpoints? 5 is a bit on the low side IMO...

**Comment by mem48** [comment]
No the problem was with the destinations not the origins

**Comment by mem48** [comment]
I've now added POIs to the teams folder. I've added a variable workplace which is my subjective judgment on if we should use them as a workplace.

**Comment by Robinlovelace** [comment]
Sounds good. Didn't we use the same points for origin and destination subpoints though?

**Comment by Robinlovelace** [comment]
Observation from train: DZs are tiny

![image](https://github.com/nptscot/npt/assets/1825120/b2a28f3e-e39c-4efa-adc9-3c211c0c4482)

**Comment by Robinlovelace** [comment]
Can you confirm how this was fixed @mem48 ? 

OK, looking at the code it seems we're loading those subpoints, but why is this commented out?

https://github.com/nptscot/npt/blob/main/_targets.R#L141
