### ISSUE TITLE
Required packages

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#202]
zonebuilder is required but not installed/checkeck for at start of build. We should declare all required packages early in the workflow

**Comment by mem48** [comment]
Also odjitter

**Comment by Robinlovelace** [comment]
Can you give this one a bash @mem48 ?

**Comment by mem48** [comment]
Is this what

```
# Set target options:
tar_option_set(
  packages = c("tibble"), # packages that your targets need to run
  format = "rds" # default storage format
  # Set other options as needed.
)

```

code is for? If so an easy fix to add more packages

**Comment by Robinlovelace** [comment]
> Is this what
> 
> ```
> # Set target options:
> tar_option_set(
>   packages = c("tibble"), # packages that your targets need to run
>   format = "rds" # default storage format
>   # Set other options as needed.
> )
> ```
> 
> code is for? If so an easy fix to add more packages

Good spot. Yes, please do add required packages there.

**Comment by mem48** [comment]
Added to forthcoming PR on zones

**Comment by Robinlovelace** [comment]
Great work Malcolm! One request on GitHub workflow, can we close issues when the relevant code is on the main branch? 

If you close an issue with the message

```
Add more packages, close #202
```

In a branch, that will auto close this issue after the PR is merged. Great job in any case.
