### ISSUE TITLE
Get zone statitics

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#21]
number of cyclists for each scenario

**Comment by Robinlovelace** [comment]
And visualise them in the website.

**Comment by mem48** [comment]
@Robinlovelace I'm working on this today, As targets is not working I'm going to write my code as a function. Then it can easily be pulled into the workflow at a later date. Sound good to you?

**Comment by Robinlovelace** [comment]
> Sound good to you?

Sounds good! If you can open a separate issue on {targets} not working with the error message that could help debug it. That's not a near term priority in prep for meeting tomorrow so great plan to forge ahead with this. One other thing: can you try to fix #22 at some point? Keep us posted here and feel free to tag me although I'm snowed under today.

**Comment by Robinlovelace** [comment]
Just checking in on this @mem48 let me know if you want any input from me.

**Comment by mem48** [comment]
Getting there

![image](https://user-images.githubusercontent.com/15819577/216323223-d40c6726-a6a7-44a1-8780-3520e6d54434.png)

**Comment by Robinlovelace** [comment]
Looking really good.

**Comment by Robinlovelace** [comment]
Propensity for cycle parking addition is a great idea. Low hanging fruit. I it deserves it's own issue as is a new feature request, good chance clients will like it!

**Comment by Robinlovelace** [comment]
Can you push your changes to date and link to this issue? You can link to the issue by adding the URL of this issue in the commit message, e.g.:

`git commit -am 'Start on zone stats, see https://github.com/nptscot/npt/issues/21`

That will even work for commits in the web repo.
