### ISSUE TITLE
Uptakes don't add up

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#226]
The increase in cyclists under go-dutch is greater than the decrease in other modes. So there is a net increase in travellers.

@Robinlovelace I think you wrote `uptake.R` can you advise?

**Comment by Robinlovelace** [comment]
We're not including results for other modes yet so have only been looking at biking. Reproducible example may help.

**Comment by Robinlovelace** [comment]
Yes but the function was developed for a different project and we're not using the non-bike numbers, right? It's worth fixing but not sure if it's in scope for Phase 1.

**Comment by mem48** [comment]
There is quite a lot of work downstream that used these numbers as they were in the build and I assumed that mean they were correct

**Comment by Robinlovelace** [comment]
Probably worth fixing then. Let's catch up on this tomorrow.

**Comment by mem48** [comment]
I've been looking into this, uptake is predicted with `pct::uptake_pct_godutch_2020` which returns a number between 0 and 1. I.e `pcycle = 0.4` means 40% could cycle.

Take an example:

| All | Bike | Car | Train |
| --- | --- | --- | --- |
| 100 | 2 | 80 | 18 |

The `bicycle_go_dutch`  formula currently used is `pcycle * all + bicycle` but I think this is wrong, as it would predict 42 cyclists not 40.

The share for other modes is then calculated based on the increase in cyclists. 

`bicycle_increase_go_dutch = bicycle_go_dutch - bicycle`
and
`car_go_dutch = car - (bicycle_increase_go_dutch* car/ all)`

Simplifying this gives

`bicycle_increase_go_dutch = bicycle_go_dutch - bicycle` --> 
`bicycle_increase_go_dutch = pcycle * all + bicycle - bicycle` --> 
`bicycle_increase_go_dutch = pcycle * all`

`car_go_dutch = car - (bicycle_increase_go_dutch* car/ all)` -->
`car_go_dutch = car - (pcycle * all * car/ all)` -->
`car_go_dutch = car - (pcycle * car)`

This is why the other mode shares are coming out wrong because saying that 40% of commuters will cycle is not the same as saying that `1- 0.4` less drivers will drive.

I suggest two changes.

`bicycle_go_dutch =  max(c(pcycle * all, bicycle)`

This means that we won't predict decreasing cycling but we won't over estimate cycling either.
Then we have a mode ratio which defines the change in other modes

`mode_ratio = (all - bicycle_go_dutch)/(all - bicycle)`

For our example `mode_ratio = (100 - 40)/(100- 2) = 0.612` this means that the other modes should reduce by 61.2%

| x | All | Bike | Car | Train |
| --- | --- | --- | --- | --- |
| Before | 100 | 2 | 80 | 18 |
| After Current | 100.8 | 42 | 48 | 10.8 |
| After Proposed | 99.976 | 40 | 48.96 | 11.016 |

This fixes the overestimation problem and means the balance between other modes is maintained. In this case, the proposed solution is a slight under estimate due to rounding.

`80/18 = 4.4444`
`48/10.8 = 4.4444`
`48.96/11.016 = 4.4444`

**Comment by Robinlovelace** [comment]
Sounds good Malcolm, thanks for the detailed examples.

My thinking on this: if you do `n_cycle = bicycle + pcycle * (1 - (bicycle / all)) * all` that would prevent the value going above 1. So if 7 out of 10 people currently cycle and `pcycle` is 0.5, you would get

``` r
pcycle = 0.5
bicycle = 7
all = 10
bicycle + pcycle * (1 - (bicycle / all)) * all
#> [1] 8.5
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

if that makes sense?

Basically diminishing increase in cycling as % currently cycling approaches 100%.

**Comment by Robinlovelace** [comment]
Is this fixed now @mem48 ?
