### ISSUE TITLE
Zones don't aling with basemap

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#26]
See: https://nptscot.github.io/web/#14.39/55.98439/-3.21974

![image](https://user-images.githubusercontent.com/15819577/216373081-bd3af34e-fe40-41aa-880a-106c9a4a8c2f.png)

This also happens with R 

![image](https://user-images.githubusercontent.com/15819577/216373825-4158faea-3443-4d9d-919e-347b4d511ce6.png)

So I think there is a problem with the data

**Comment by Robinlovelace** [comment]
Maybe. Good spot, could have been the CRS transformation as the zones started life in EPSG:27700

**Comment by Robinlovelace** [comment]
Ho did you fix this @mem48 ? Good job in any case.
