### ISSUE TITLE
Failing ROutes

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#260]
Some routes are failing e.g.

```
C:\Users\earmmor\AppData\Local\Temp\Rtmp422ovE/test.csv.gz
Removing NA routes: 4931 7931 8855 12542 14292 25738 28302 29277 32959 35373 38796 41561 47187 48501 59438 68319 68407 73334 79324 79366 82467 84317 86292 86664 86804 93451 93468 95916 113738 115608 122278 122295 126869 133017 139848 139852 140005 140221 145732 164441 165937 186149 189960 202512 211857 214316 214788 214803 214922 215838 216312 216727 231494 231687 240185 240235 240294 242021 242657 262992 305233 306175 353283 353421 353621 353951 363022 384401 384487 384621 386054 386229 396469 396971 397651 398001 398934 402097 420322 427888 428514 428877 430169
When using segments = both, only the routes are joined to desire lines
83 routes removed

```

I think this is jittering making unroutable ODs. Should check these and remove unacceptable sub-points.

**Comment by Robinlovelace** [comment]
Good thinking. Do you know what % of routes that is? I think if less than 0.1% it's unlikely to have any impact on the results. Do investigate if you get time @mem48 but not a priority IMO. Any thoughts on identifying/debugging these @mvl22? We should be able to send you the OD pairs associated with the failing routes listed above to check.

**Comment by mem48** [comment]
I've updated the OS POIs, a small number of them are in unrouteable locations.

**Comment by Robinlovelace** [comment]
> I've updated the OS POIs, a small number of them are in unrouteable locations.

Do you have the code that does this? Input data is sacred so we should add code to modify raw input data rather than updating input files on an ad-hoc basis.
