### ISSUE TITLE
Build crashes if internet drops

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#261]
If your internet connection drops the routing functions fail.

```
Getting the balanced routes for commute journeys
POSTing the request to create and start the job
Job id: 5853
No data returned yet. Trying again id 5853 every 10 seconds
Sending data, wait...
Routing not complete
✖ error target r_commute_rns
▶ end pipeline [5.932 hours]
|here were 11 warnings (use warnings() to see them)
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Timeout was reached: [api.cyclestreets.net] Send failure: Connection was reset

```

Given that we are waiting for cycle streets there is no reason to crash, code should just wait a bit and try again

**Comment by Robinlovelace** [comment]
Isn't it save to assume that computers running the code are connected to the internet. Happy for a PR that solves this but I don't think it's a priority and happy for this to be a wontfix. There may be some reasons that I'm not aware of to prioritise this so leaving open for now, thanks for flagging @mem48 and let me know your thoughts on next steps if any on this edge-case issue. More importantly how goes the build?

**Comment by mem48** [comment]
Shouldn't be hard, just need to wrap a try function around
https://github.com/nptscot/cyclestreets-r/blob/dcb7bd0fdf91f959c297b82990c9af32a276c7ce/R/batch.R#L179

**Comment by Robinlovelace** [comment]
> Shouldn't be hard, just need to wrap a try function around https://github.com/nptscot/cyclestreets-r/blob/dcb7bd0fdf91f959c297b82990c9af32a276c7ce/R/batch.R#L179

Aha, great. From that it seems I *did* write a function to delete jobs. Worth exposing that as an `@export`ed function?

https://github.com/nptscot/cyclestreets-r/blob/dcb7bd0fdf91f959c297b82990c9af32a276c7ce/R/batch.R#L196

**Comment by Robinlovelace** [comment]
Issue opened upstream: https://github.com/cyclestreets/cyclestreets-r/issues/81

**Comment by mem48** [comment]
An additional fix would be to check less often when a long wait is expected.  For example, if know the best rate is 50 routes per second wait for `nroutes / 50` seconds before checking every 10 seconds. That would prevent a mid-routing loss of connection from having any effect on the build.

**Comment by Robinlovelace** [comment]
Can be fixed upstream, the 1000 here could be reduced, e.g. to 200: https://github.com/cyclestreets/cyclestreets-r/blob/master/R/batch.R#L417
