### ISSUE TITLE
Ebike scenario network is gappy

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#267]
As illustrated below.

![image](https://github.com/nptscot/npt/assets/1825120/87aad9df-129a-47c9-95da-97fc0189b327)

Source: https://nptscot.github.io/#15.09/55.94352/-3.24

**Comment by mem48** [comment]
Fixed, the problem was with the sliders the max value was set to 5,000 so roads with more cyclists were being filtered out. Raised to 20,000. The current highest value is 9,064 so should give headroom for additional trip purposes.

**Comment by Robinlovelace** [comment]
Great fix :tada:
