### ISSUE TITLE
Split routing from loading routes

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#275]
A commute routing batch takes about 3.5 hours, but of that around 30+ minutes is post-processing e.g. `batch_read`.

This is wasted time that the new routing could have been sent to the cycle streets server, so I suggest we fix this by:

Target 1; Sends routing requests and downloads results, returns path to saved results
Target 2: Reads results and joins on desire line variables. 

With the new parelleised build this should shave another 2 hours of the total build time.

**Comment by Robinlovelace** [comment]
Another option: use `batch_multi()` and fix it upstream.

This function may need some tweaks for that: https://github.com/cyclestreets/cyclestreets-r/blob/master/R/batch_multi.R#L32

**Comment by mem48** [comment]
To be honest I get a bit confused with the logic of the batch functions. But there must be a stage where you have downloaded the file. That you could put in a
```
if(load_data = FALSE){
     return(file_path)
}
```

**Comment by Robinlovelace** [comment]
No, the point is to send all the requests at the beginning and then download them one-by-one.
