### ISSUE TITLE
School Ebike uptake is lower than Go dutch

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#279]
![image](https://github.com/nptscot/npt/assets/15819577/34d67cd1-96b2-4b78-891a-160b288d0bc5)

**Comment by mem48** [comment]
We discussed this as the ebike scenario uses the commuting model, but Children can't ride ebikes legally so this is more of a parent takeing there children on a ebike scenario

**Comment by Robinlovelace** [comment]
Maybe worth saying that in the documentation?

**Comment by Robinlovelace** [comment]
Food for thought @mem48 and @wangzhao0217 https://twitter.com/CoachBalto/status/1707540157132644525
