### ISSUE TITLE
Move more layers into the main build

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#281]
- [x] Datazones
- [x] Buildings (Daysemetric zones)
- [ ] School points
- [ ] Admin boundaries (low priority as rarely changes)
- [ ] Basemap (low priority as rarely changes)
- [ ] Terrain ((low priority as rarely changes)

**Comment by mem48** [comment]
test code

https://github.com/nptscot/npt/blob/main/code/dasymetric.R
https://github.com/nptscot/npt/blob/main/code/dasymetric_join.R
https://github.com/nptscot/npt/blob/main/code/dasymetric_part2.R

**Comment by mem48** [comment]
Be careful some of these stages take ages and need large RAM

**Comment by mem48** [comment]
https://github.com/nptscot/npt/blob/main/code/prep_school_data.R

**Comment by mem48** [comment]
https://github.com/nptscot/npt/blob/main/code/tests/import_SMID.R

**Comment by Robinlovelace** [comment]
Aha great, this was discussed this morning. Another idea discussed with @mem48: a `tippecanoe` function, and possibly mini package to host it.
