### ISSUE TITLE
Authority level views

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#29]
Currently we have https://nptscot.github.io/web/#12.68/56.46846/-2.93715

As discussed with the client it could be good to have subfolders like https://nptscot.github.io/web/dundee 

That's currently what we have here: https://cruse.bike/kildare/

**Comment by mem48** [comment]
This is a lot of extra work and I don't see the benefit. Perhaps I'm misunderstanding, but I though the county-level approach was due to technical limitations.

**Comment by Robinlovelace** [comment]
> This is a lot of extra work and I don't see the benefit. Perhaps I'm misunderstanding, but I though the county-level approach was due to technical limitations.

It wasn't that much extra work. It wasn't for technical limitations. It was to provide extra county-specific information for counties, in addition to the vector tiles in the landing page at cruse.bike. @joeytalbot and I implemented it in a `for()` loop over each county. We can discuss.

**Comment by Robinlovelace** [comment]
Follow-up question for Joey: something you're happy to look at?
