### ISSUE TITLE
Issue remains on rnet_merge

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/npt#297]
1. rnet_merge have difficulty handling winding roads:https://nptscot.github.io/#15.31/55.940009/-3.160612/12.8
![image](https://github.com/nptscot/npt/assets/74598734/271b6f78-880a-403b-834d-fc08655edca9)
![image](https://github.com/nptscot/npt/assets/74598734/395a9d00-6c5d-40f4-becc-f673e3014ec7)

2. the original npt network need a cleaning: https://nptscot.github.io/#18.02/55.955219/-3.112336/12.8
![image](https://github.com/nptscot/npt/assets/74598734/7a9a2c0a-6eff-4aa9-95e6-8eccd38c4472)

3. is there a need to introduce line_segment on rnet_x in rnet_join?
```{r}
rnet_join <- function(rnet_x, rnet_y, dist = 5, length_y = TRUE, key_column = 1,
                      subset_x = FALSE, dist_subset = NULL, segment_length = 0,
                      endCapStyle = "FLAT", contains = TRUE, max_angle_diff = NULL,
                      crs = geo_select_aeq(rnet_x), ...) {
  if (is.null(dist_subset)) {
    dist_subset <- dist + 1
  }
  if (subset_x) {
    rnet_x <- rnet_subset(rnet_x, rnet_y, dist = dist_subset, ...)
  }
  # if (segment_length > 0) {
  #   print('rnet_x is being segmented')
  #   rnet_x <- line_segment(rnet_x, segment_length = segment_length)
  #   rnet_x = st_make_valid(rnet_x)
  # }  
  if (!is.null(max_angle_diff)) {  
    rnet_x$angle_x <- line_bearing(rnet_x, bidirectional = TRUE)
    contains <- FALSE
  }
  rnet_x_buffer <- geo_buffer(rnet_x, dist = dist, nQuadSegs = 2, endCapStyle = endCapStyle, crs = crs)
  if (segment_length > 0) {
    print('rnet_y is being segmented')
    rnet_y <- line_segment(rnet_y, segment_length = segment_length)
  }
  if (!is.null(max_angle_diff)) {
    rnet_y$angle_y <- line_bearing(rnet_y, bidirectional = TRUE)
  }
  if (length_y) {
    rnet_y$length_y <- as.numeric(sf::st_length(rnet_y))
  }
  if (contains) {
    rnetj <- sf::st_join(rnet_x_buffer[key_column], rnet_y, join = sf::st_contains)
    # # For debugging:
    # library(tmap)
    # tmap_mode("view")
    # tm_shape(rnet_y) + tm_lines(lwd = 3) + qtm(rnetj) + qtm(rnet_x) +
    #   qtm(osm_net_example)
  } else {
    rnet_y_centroids <- sf::st_centroid(rnet_y)
    rnetj <- sf::st_join(rnet_x_buffer[c(names(rnet_x)[1], "angle_x")], rnet_y_centroids)
  }
  if (!is.null(max_angle_diff)) {
    rnetj$angle_diff <- rnetj$angle_y - rnetj$angle_x
    rnetj <- rnetj[abs(rnetj$angle_diff) < max_angle_diff, ]
  }
  rnetj
}
```
4. introduce adaptive buffer size based on road class, e.g. 20 m for Forth Bridges and 10 m for city centre.

**Comment by Robinlovelace** [comment]
Thanks for these comments Zhao, great details, and good discovery regarding winding roads, I hadn't thought of that.

> 1. rnet_merge have difficulty handling winding roads:https://nptscot.github.io/#15.31/55.940009/-3.160612/12.8

Interesting issue. I can think of a few possible solutions but not sure they will work. What do you think?

> 2. the original npt network need a cleaning: https://nptscot.github.io/#18.02/55.955219/-3.112336/12.8

That's not a simplification issue. Interested to hear what Malcolm thinks.

> 3\. is there a need to introduce line_segment on rnet_x in rnet_join?

I'm not sure what you mean. On the main branch the lines are uncommented: https://github.com/ropensci/stplanr/blob/master/R/rnet_join.R#L100 Please clarify @wangzhao0217.

Overall: great work.

**Comment by wangzhao0217** [comment]
> Thanks for these comments Zhao, great details, and good discovery regarding winding roads, I hadn't thought of that.
> 
> > 1. rnet_merge have difficulty handling winding roads:https://nptscot.github.io/#15.31/55.940009/-3.160612/12.8
> 
> Interesting issue. I can think of a few possible solutions but not sure they will work. What do you think?
> 
> > 2. the original npt network need a cleaning: https://nptscot.github.io/#18.02/55.955219/-3.112336/12.8
> 
> That's not a simplification issue. Interested to hear what Malcolm thinks.
> 
> > 3. is there a need to introduce line_segment on rnet_x in rnet_join?
> 
> I'm not sure what you mean. On the main branch the lines are uncommented: https://github.com/ropensci/stplanr/blob/master/R/rnet_join.R#L100 Please clarify @wangzhao0217.
> 
> Overall: great work.

Regarding 3. is there a need to introduce line_segment on rnet_x in rnet_join? https://github.com/ropensci/stplanr/blob/master/R/rnet_join.R#L100  

The line_segment is applied to rnet_y, but not to rnet_x. In rnet_x, there are notably long segments, such as the one shown here:
![image](https://github.com/nptscot/npt/assets/74598734/6bfc3fa0-6155-47c1-b88d-0187e8e5a851)
This might lead to inaccurate calculations when executing rnet_x$angle_x <- line_bearing(rnet_x, bidirectional = TRUE). Such inaccuracies could result in winding roads receiving a lower value.

However, when I tried segmenting rnet_x before joining, the results didn't seem quite right (As shown below, the blue numbers represent the results after segmenting rnet_x by 400, while the red numbers indicate the results when rnet_x is not segmented).
![image](https://github.com/nptscot/npt/assets/74598734/abcb0cda-ff01-4f7b-9f43-4a9824a17285)

I haven't determined the reason yet, but I'll continue to investigate. Is there a specific reason rnet_x isn't segmented in stplanr?

**Comment by Robinlovelace** [comment]
> This might lead to inaccurate calculations when executing rnet_x$angle_x <- line_bearing(rnet_x, bidirectional = TRUE). Such inaccuracies could result in winding roads receiving a lower value.

Good point. Yes: I think we should pre-process `rnet_x` before running `rnet_merge(rnet_x, rnet_y)`.

**Comment by Robinlovelace** [comment]
> Is there a specific reason rnet_x isn't segmented in stplanr?

No specific reason but the need is for the old geometry (`rnet_y`) to have centroids within the new geometry (`rnet_x`). 

We can segment `rnet_x` before merging. However, that would mean the results are not faithful to the source of the new geometry. There are advantages of being 100% faithful to Ordance Survey, right?

It's an interesting idea and happy to see reproducible examples where it makes a difference. However, may not be a priority and I can think of other work-around solutions, e.g. use the original geometry in cases where the new geometry is unusually long.

**Comment by Robinlovelace** [comment]
@wangzhao0217 are there any next steps on this? I'm closing in favour of #323 but we can re-open this if needs be. Please comment here or in #323 regarding any next steps that we can take to improve the simplified network.
