### ISSUE TITLE
Variaible line widths

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#30]
Now implemented

![image](https://user-images.githubusercontent.com/15819577/216691149-5c6bf04a-4245-47e3-a0ed-c95fd9ed33de.png)

How good it looks depends on the combination of colours and widths.

![image](https://user-images.githubusercontent.com/15819577/216691370-9fd9f2a6-bd06-496b-8579-8c8d1bc4465c.png)
 
Widths are coded by:

```
'line-width': [
                'interpolate', 
                ['linear'], 
                ['zoom'],
                12, ["*", 2.1 , a, ["^", ["+", 1, ["get", layerWidth]], b]],
                14, ["*", 5.25, a, ["^", ["+", 1, ["get", layerWidth]], b]],
                15, ["*", 7.5 , a, ["^", ["+", 1, ["get", layerWidth]], b]],
                16, ["*", 18  , a, ["^", ["+", 1, ["get", layerWidth]], b]],
                18, ["*", 52.5, a, ["^", ["+", 1, ["get", layerWidth]], b]], 
                22, ["*", 150 , a, ["^", ["+", 1, ["get", layerWidth]], b]]
            ],
```
Where `a` and `b` form the function `width = a * value ^ b` and have to be adjusted for each layer.

**Comment by mem48** [comment]
Also a `none` option

![image](https://user-images.githubusercontent.com/15819577/216692555-3133b1e7-112f-4cb8-9b00-6e549c4d79de.png)

Which is as before

**Comment by Robinlovelace** [comment]
Great progress. Look forward to giving it a spin and hearing what people think, confident this is a step in a good direction and personally: really like the variable line widths so far, especially for red/green colours.
