### ISSUE TITLE
Get full balanced, quietest, ebike networks

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#31]
Currently we have the full fastest network but only a sample of routes in the balanced network.

**Comment by mem48** [comment]
Head up @Robinlovelace routing for balance, quiet, and ebikes is now done thanks to `journey2` 

https://github.com/nptscot/inputdata/releases/tag/routes_commute

Speed dropped to 10 routes/second on larger runs which is not great but still fast enough to do a national build overnight. An crucially doesn't crash. I can probably squeeze out a few more performance improvements if needed.

The `journey2` function does not return identical results to `journey` so some post-processing will have to be done for gradients etc. But all the necessary data should be there.

If you can get the rnets / scenarios built today I'll work on UI and we can upload the new data tomorrow.

**Comment by Robinlovelace** [comment]
> If you can get the rnets / scenarios built today I'll work on UI and we can upload the new data tomorrow.

Sounds good. Key question: where is the reproducible code underlying this?

**Comment by mem48** [comment]
https://github.com/nptscot/npt/blob/main/code/commute_routing.R

**Comment by Robinlovelace** [comment]
Giving this a go now...

![image](https://user-images.githubusercontent.com/1825120/218805529-2c668143-9e88-4f5c-a31d-6e9c8d76de68.png)

**Comment by Robinlovelace** [comment]
New batch routing function works well. Seems this is the one that failed. From `tar_make()`:

batch_balanced_commute_0698_with_100_routes_of_112567_rows.Rds

Re-running `tar_make()` again it just picked up where it left off meaning no time lost:

![image](https://user-images.githubusercontent.com/1825120/219162195-1f2bb346-a078-4a5f-9770-9e767ad87379.png)

**Comment by Robinlovelace** [comment]
Balanced network: done https://github.com/nptscot/outputdata/releases/tag/v2023-02-16-21-10-53_commit_64e82a37dffe23dffeb2324bb9c768e488e8cd3c

**Comment by Robinlovelace** [comment]
Getting some good results with `batch()` for all route types:

![image](https://user-images.githubusercontent.com/1825120/219509528-116182a7-f417-4b92-b574-9ea24665f291.png)

**Comment by Robinlovelace** [comment]
Trying to do all routes in 10 lots of 10k, for all route types.

![image](https://user-images.githubusercontent.com/1825120/219510304-311cce9a-8bba-436c-b893-2610c8a7a482.png)

**Comment by Robinlovelace** [comment]
`batch()` is the fastest way for anything above ~2k routes.

![image](https://user-images.githubusercontent.com/1825120/219510883-5fdc0d5a-280b-444b-b944-abb77c5ba2c0.png)

**Comment by atumscott** [comment]
@mem48 the networks are done with combined rnet here: https://github.com/nptscot/outputdata/releases/tag/full-net-fast-track

I've re-opened the issue and assigned to you because we should only see this as done when the data is up on the website.

**Comment by atumscott** [comment]
We just need to run these lines of code on it: 

https://github.com/nptscot/npt/blob/2d2bb56f2e4ced52679f13507c352de8fe589f9d/_targets.R#L205-L245

**Comment by atumscott** [comment]
I cannot run those lines of code for some reason, getting a crash on the overline line:

https://github.com/nptscot/npt/blob/2d2bb56f2e4ced52679f13507c352de8fe589f9d/_targets.R#L227

Result: 

![image](https://user-images.githubusercontent.com/119737782/220049893-f96ae498-9a8e-4d86-968c-08ab25b016b6.png)

Can you try your end and report back?

**Comment by atumscott** [comment]
Update, it's finally worked. The combined network can be found here: https://github.com/nptscot/outputdata/releases/download/full-net-fast-track/rnet_commute_list.Rds

Closing for now. Will re-open another issue on getting the data on the website.
