### ISSUE TITLE
Create new target in `_targets.R` that reads-in summarised Scottish Household Travel Survey data (and possibly NTS data showing COVID rebound).

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#327]
This is a good place to start I think @juanfonsecaLS1, up for giving it a bash? I'm around tomorrow if you want to chat it over.

**Comment by Robinlovelace** [comment]
Key thing is to tie down the links between detailed purposes in the Scottish Travel Survey and the 3 purposes that @joeytalbot is working on. Most relevant bit from Juan's work: https://github.com/nptscot/TT_-Scottish_Household_Survey#annualisation-factors-calculation

:+1: to using expansion factors for all modes, not just cycling. Question that I think the data can answer: how different are the expansion factors for cycling vs expansion factors averaged across all modes. Would be good to chat this through in person.

**Comment by Robinlovelace** [comment]
Can you produce a table with the SHTS categories associated with

- "Shopping"
- "Visiting"
- "Leisure" (the most ambiguous)

before we meet Juan that would be amazing.

**Comment by juanfonsecaLS1** [comment]
Done, I updated the table for both bike and all other modes

**Comment by Robinlovelace** [comment]
Awesome, let's catch up tomorrow.

**Comment by Robinlovelace** [comment]
Good reference point for this: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1180762/nts0403.ods

**Comment by Robinlovelace** [comment]
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1180762/nts0403.ods

**Comment by Robinlovelace** [comment]
https://www.gov.uk/government/statistical-data-sets/nts04-purpose-of-trips

**Comment by Robinlovelace** [comment]
This is great stuff Juan, impressive use of equations in GitHub issues also!

**Comment by Robinlovelace** [comment]
Ideas for columns in the table, with one row per purpose:

- Expansion factor, converting n. commuters to actual n. trips for commuting and school, and number of trips per person per day for other trip purposes
- Total number of trips across Scotland (previous column x total population of Scotland)
- Trips per week per purpose
- Trips by bike 
- Number of outbound
- Number of inbound

**Comment by Robinlovelace** [comment]
Recreational?

**Comment by juanfonsecaLS1** [comment]
I created the file in the `data-raw` and updated the analysis in the TT SHS repo.

**Comment by Robinlovelace** [comment]
Great job Juan, we can close this when that is merged.

**Comment by juanfonsecaLS1** [comment]
Done, I will close it with this. I have added the Recreational cycling to the analysis and the directions to wrap this up.
