### ISSUE TITLE
Requirements for reproducing the open data results

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#334]
Notes on how to reproduce the results:

- [ ] CycleStreets API key: https://rpackage.cyclestreets.net/reference/journey.html
- [ ] R/RStudio installation
- [ ] Optional but worth testing: VS Code + Devcontainers: https://code.visualstudio.com/docs/devcontainers/tutorial

**Comment by Robinlovelace** [comment]
https://r.geocompx.org/transport.html

**Comment by HemantSharmaTP** [comment]
That's very helpful. Thank You, Robin. I will try this.

**Comment by Robinlovelace** [comment]
Thanks @HemantSharmaTP, let us know the error message you see when it inevitable fails: full reproducibility in this repo is work in progress!
