### ISSUE TITLE
Enable routing when batch service maxxed out

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#338]
As reported by @mem48, our ability to reproduce small builds is reduced when the service is maxxed out. Solution: turn batch routing off. I plan to put in a PR with a quick fix for this.

**Comment by Robinlovelace** [comment]
There are 2 solutions:

- Set max to route here to 49 or less:

https://github.com/nptscot/npt/blob/2a563c5fe53f09caf8d74648e625fbe68e8f229e/parameters.json#L4

- Set `batch = FALSE` here:

https://github.com/nptscot/npt/blob/2a563c5fe53f09caf8d74648e625fbe68e8f229e/R/get_routes.R#L1

Does that fix it for you @mem48 ? should do.

**Comment by mem48** [comment]
I'm trying with 49 routes. But from memory the outputs from batch = FALSE were not the same

**Comment by mem48** [comment]
Yes the routes & segments are not returned when `batch = FALSE`

**Comment by Robinlovelace** [comment]
Oh yeah.

**Comment by Robinlovelace** [comment]
Let's pause the national build I'm thinking.

**Comment by Robinlovelace** [comment]
Closing as fixed by re-scheduling jobs.
