### ISSUE TITLE
Multiple Base Maps

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#34]

**Comment by mem48** [comment]
https://github.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets

**Comment by mem48** [comment]
Its a bit buggy but its looks good

![image](https://user-images.githubusercontent.com/15819577/217921750-85552115-2b3c-4ef2-9753-af0794785ac8.png)

**Comment by mem48** [comment]
And you can't do that in the PCT/Cruse 🤣

**Comment by Robinlovelace** [comment]
Cool! How do I give it a spin?

**Comment by Robinlovelace** [comment]
OK see it's up. Looking good but seems flat as a pancake for Edinburgh.

![Uploading image.png…]()

Source: https://nptscot.github.io/web/#15.79/55.940899/-3.205096/-64.8/83

**Comment by mem48** [comment]
Have you pressed the 3D terrain button?

**Comment by Robinlovelace** [comment]
> Have you pressed the 3D terrain button?

Aha nope, will give it a spin.

**Comment by Robinlovelace** [comment]
This is so cool :heart_eyes: 

https://nptscot.github.io/web/#16.12/56.153089/-3.823172/-76.8/77
