### ISSUE TITLE
find_odjitter_location does not work

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#344]
On my PC `find_odjitter_location()` get the wrong results is this a windows/linux thing? The default of "odjitter" works fine

**Comment by mem48** [comment]
@joeytalbot I think this was your change? https://github.com/nptscot/npt/commit/7b7f2f0733dcd458c5c59bf344ba248dee78510b

**Comment by mem48** [comment]
```
> is_bin_on_path("odjitter")
[1] FALSE

```

**Comment by mem48** [comment]
```
> bin = "odjitter"
> system2("command", args = c("-v", bin), stdout = FALSE)
> exit_code = suppressWarnings(system2("command", args = c("-v", bin), stdout = FALSE))
> exit_code 
[1] 127

```

**Comment by mem48** [comment]
This works

```
> system("odjitter -V")
odjitter 0.1.0

```

**Comment by Robinlovelace** [comment]
Any thoughts on a quick fix @mem48 ?

**Comment by Robinlovelace** [comment]
127 does seem to mean "not found": https://stackoverflow.com/questions/1763156/127-return-code-from

**Comment by Robinlovelace** [comment]
Something to do with WSL?
