### ISSUE TITLE
Error message generated by simplify target

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#350]
As described by @mem48 here: https://github.com/nptscot/npt/pull/345#issue-2028578831

I'll share a permalink to the code below.

**Comment by Robinlovelace** [comment]
Just trying to get a permalink...

![image](https://github.com/nptscot/npt/assets/1825120/2b336da1-118a-4c94-8433-c29a0eb0b3b3)

Source: https://github.com/nptscot/npt/blob/main/_targets.R#L1526-L1530

**Comment by Robinlovelace** [comment]
Let's see what happens when we try running the code.

**Comment by Robinlovelace** [comment]
OK just needed to load the tidyverse...

**Comment by Robinlovelace** [comment]
Currently waiting on this:

```
>   rnet_merged_all_geos_buffer = geos::geos_buffer(rnet_merged_all_geos, distance = 30)
```

How long did that take on your computer @wangzhao0217 ?

**Comment by wangzhao0217** [comment]
About half an hour

**Comment by wangzhao0217** [comment]
No sorry Robin, to create the buffer is quick, to find the line within that
process is taking half an hour

**Comment by Robinlovelace** [comment]
https://github.com/nptscot/npt/blob/7c572b8008a5f9d6381de88c468fc52e958d582c/test-simplify-target.qmd#L5-L154
