### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#359]
There is agreement that NPT needs a logo but no one can agree on what. So I've made one as a placeholder. Happy to change if people have better ideas.

![npt_logo](https://github.com/nptscot/npt/assets/15819577/7e00d51e-d929-4b06-99a0-7ac307cfaff8)

**Comment by Robinlovelace** [comment]
Not bad for a placeholder! @Mattpdavis and Angus thoughts?

**Comment by Robinlovelace** [comment]
One option that's worked for projects I've worked on before is crowd sourcing designs via a logo competition, also a good way to get people interested and engage. Example: https://geocompx.org/post/2023/map-cover-competition/
