### ISSUE TITLE
Iteration on coherent network results

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#391]
In conversation with Angus and Malcolm, we're talking about improving this result from a policy perspective.

- [x] Overall it should mostly be arterial
- [ ] Would be nice if it could grow

![image](https://github.com/nptscot/npt/assets/1825120/0f97e98b-edbb-4c13-aec3-b0927638f758)

**Comment by Robinlovelace** [comment]
We should adjust the settings so that we don't include lots of residential / off road routes:

![image](https://github.com/nptscot/npt/assets/1825120/67b62859-2277-4fe3-9aa6-257706bf7877)

**Comment by Robinlovelace** [comment]
Ideas on how to do this can be found in this paper by @szell (any input welcome Michael!): http://arxiv.org/abs/2107.02185

**Comment by mszell** [comment]
Very nice tool! Thx for asking. In our project we had the same issue with such residential zig-zag paths. I don't have _the_ solution but there could be different methods to resolve this. We are experimenting with COIN right now, for example: https://journals.sagepub.com/doi/10.1177/2399808320967680 (implemented in momepy). Or, a heuristic could be to penalize turns or to improve certain metrics. All work in progress, happy to let you know our preliminary results once we have some..

**Comment by Robinlovelace** [comment]
Awesome, thanks for the suggestion and quickfire response Michael, can keep you posted as things progress! @wangzhao0217 literally working on this with me right now, hope to be able to share ideas back with the community at some point..

**Comment by Robinlovelace** [comment]
Reviving this in conversation with @wangzhao0217. We're in a good place, with an MVP UI deployed on the test website thanks to great work by @mvl22 shown below.

However, the groups do not make sense from a transport planning perspective. Group 1 should be what you build first but currently the group orders are random. And groups are more like areas, rather than the 'skeleton' of the network for the first groups and the 'leaves' for the latter groups in the cohesive network, as described in the GrowBike method and paper by @mszell.

The first group should represente the bit that transport planners should build first. Which is usually from the centre, or from the largest residential area to the economic centre, along the route/corridor with the highest demand.

This is what we have currently:

![image](https://github.com/nptscot/npt/assets/1825120/3b004a42-d978-44c6-9565-f42fced9b123)

Source: https://nptscot.github.io/#/cohesivenetwork/#11.67/55.9385/-3.184

Thoughts on best next steps on this very welcome.

**Comment by Robinlovelace** [comment]
BTW @mvl22 good example of the dynamic URLs that change when layers are changed. Should the Cohesive network UI element not be expanded though? Reproducible example: click on the link above and you see this:

![image](https://github.com/nptscot/npt/assets/1825120/7fe671a8-b6b1-4bee-a1c0-1cde955f2ff7)

However you should see something more like this I think:

![image](https://github.com/nptscot/npt/assets/1825120/c1a209e5-5271-451b-a1b2-6469547ba4cc)

Right? We should track this in the UI codebase if so.

**Comment by mvl22** [comment]
Yes.

I haven't yet reworked the accordion to have a proper hierarchical relationship between the titles, the layer-enabling buttons and the controls within layers. Once that is done, auto-opening a section, and indeed getting the parameter-level URLs in place will be possible.

**Comment by Robinlovelace** [comment]
Latest comments from @anguscalder:

![image](https://github.com/nptscot/npt/assets/1825120/2cd703f0-45d7-4913-b712-7e0166a21090)

We should get more continuity, e.g. making the path continue.
