### ISSUE TITLE
Run tar_make()

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/npt#392]
Stucking at step ebike primary for a very long time.
An error message from docker: 
![Screenshot 2024-01-21 095638](https://github.com/nptscot/npt/assets/74598734/67d569d0-467e-446c-bd5b-55b6c2c95201)

will try again.

**Comment by Robinlovelace** [comment]
Thanks for the heads-up and good luck with it.

**Comment by wangzhao0217** [comment]
This time stuck on another step for a long time (15hours). any suggestions? 
![image](https://github.com/nptscot/npt/assets/74598734/fe0adbdd-9a6b-4b39-911c-3b1dbcb8243b)

**Comment by Robinlovelace** [comment]
Not sure, thanks for testing Zhao, let's look into it.

**Comment by wangzhao0217** [comment]
stuck on completed target rnet_primary_ebike [41.46 seconds] for more than 12 hours...
![image](https://github.com/nptscot/npt/assets/74598734/c174b635-4034-4aa2-ab2d-ecc0f047eff0)

**Comment by wangzhao0217** [comment]
I have attempted twice but kept stuck on this step:
![image](https://github.com/nptscot/npt/assets/74598734/ca7761db-d272-41ba-bf2e-f2ba85d3389a)

**Comment by Robinlovelace** [comment]
It's the `school_stats` that is stuck I think @wangzhao0217.
