### ISSUE TITLE
rnet outputs capitalised variables inconsistently

### ISSUE THREAD

**Issue by mvl22** [nptscot/npt#395]
The `rnet` dataset has two fields that, unlike all others, are capitalised: 'Quietness' and 'Gradient'.

This means that the website codebase has various places where this has to have special-case code to swap from lower-case to upper-case:

```
      'quietness': [
        "step", ["get", "Quietness"],
```

making it harder to convert various datastructures to be self-referencing or auto-created.

Can these be fixed up?

**Comment by Robinlovelace** [comment]
> Can these be fixed up?

Sure thing happy to fix this one. All lowercase in next data release.

**Comment by Robinlovelace** [comment]
@wangzhao0217 can you take a look at this when you get a chance?

**Comment by wangzhao0217** [comment]
@Robinlovelace I directly pushed a fix to the main branch for an issue in 'rnet_functions.R', instead of using a new branch and a pull request. Sorry about that. I'll make sure to follow the correct process next time. Another question: Should I apply the fix across the entire NPT ?

**Comment by Robinlovelace** [comment]
> Another question: Should I apply the fix across the entire NPT ?

Yes but do it as a Pull Request rather than pushing directly to the main branch :+1:

**Comment by wangzhao0217** [comment]
solved in the latest push

**Comment by Robinlovelace** [comment]
Great job Zhao :fire:
