### ISSUE TITLE
tar_make() error

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/npt#405]
Hi Robin,

 I keep seeing pop-up windows for target school_stats_json. Does this have any connection? 
![Screenshot 2024-02-05 001032](https://github.com/nptscot/npt/assets/74598734/b2568548-c30c-481c-ab34-0f6203ae38f5)

This morning, I discovered this error, but the Docker crashed.

✔ skipped target school_stats_from_ebike
✔ skipped target school_stats_from
✔ skipped target rnet_secondary_ebike
✔ skipped target rnet_primary_ebike
✔ skipped target school_stats_ebike
✔ skipped target school_stats
✔ skipped target school_stats_json
✖ errored target rs_commute_fastest
✖ errored pipeline [5.006 hours]
Warning messages:
1: 4 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
2: In file(file, mode) :
  cannot open file '/tmp/Rtmp0T0Ufh/callr-res-430413f4b1': Read-only file system
3: In gzfile(file, mode) :
  cannot open compressed file '/tmp/Rtmp0T0Ufh/callr-res-430413f4b1.error', probable reason 'Read-only file system'
rm: cannot remove '/tmp/RtmpKB4H7Z/libloc_180_a38f7d5813344af9.rds': Read-only file system
rm: cannot remove '/tmp/RtmpKB4H7Z/libloc_175_567e7dd1125c9f1e.rds': Read-only file system
-
 *** caught bus error ***
address 0x7f9a6f7a2cd0, cause 'non-existent physical address'
An irrecoverable exception occurred. R is aborting now ...
rm: cannot remove '/tmp/RtmpKB4H7Z/libloc_180_a38f7d5813344af9.rds': Read-only file system
rm: cannot remove '/tmp/RtmpKB4H7Z/libloc_175_567e7dd1125c9f1e.rds': Read-only file system
Error in `get_result(output = out, options)`:
! callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
ℹ See `$stderr` for standard error.
Type .Last.error to see the more details.

**Comment by Robinlovelace** [comment]
Hi Zhao, yes that looks like it. Maybe try changing the location of input and output files.

**Comment by wangzhao0217** [comment]
● completed target param_file [0.928 seconds]
▶ dispatched target parameters
● completed target parameters [0.025 seconds]
▶ dispatched target study_area
● completed target study_area [0 seconds]
▶ dispatched target os_pois
▶ dispatched target zones
▶ dispatched target od_school
● completed target od_school [0.47 seconds]
▶ dispatched target rs_school_fastest
✔ skipped target school_stats_from_baseline
✔ skipped target school_stats_baseline
● completed target os_pois [2.821 seconds]
✔ skipped target od_leisure
✔ skipped target od_shopping
✔ skipped target od_visiting
✖ errored target rs_school_fastest
✖ errored pipeline [15.462 seconds]
Error:
! Error running targets::tar_make()
Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
Debugging guide: https://books.ropensci.org/targets/debugging.html
How to ask for help: https://books.ropensci.org/targets/help.html
Last error message:
    ReadItem: unknown type 84, perhaps written by later version of R
Last error traceback:
    get_routes(od = od_school %>% slice_max(n = parameters$max_to_route,    ...
    readRDS(savename_f)
    .handleSimpleError(function (condition)  {     state$error <- build_mess...
    h(simpleError(msg, call))

> targets::tar_meta(fields = error, complete_only = TRUE)
# A tibble: 1 × 2
  name              error                                                       
  <chr>             <chr>                                                       
1 rs_school_fastest ReadItem unknown type 84, perhaps written by later version …

![image](https://github.com/nptscot/npt/assets/74598734/83e9f287-bfad-4a8f-aa05-0f8a9ccafb7c)
![image](https://github.com/nptscot/npt/assets/74598734/ca296897-01bf-44c9-94b5-29661756b953)

**Comment by wangzhao0217** [comment]
just tried again, got error:
✔ skipped target commute_stats_baseline
✖ errored target rs_school_fastest
✖ errored pipeline [2.352 minutes]
Warning message:
3 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
Error:
! Error running targets::tar_make()
Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
Debugging guide: https://books.ropensci.org/targets/debugging.html
How to ask for help: https://books.ropensci.org/targets/help.html
Last error message:
    Timeout was reached: [api.cyclestreets.net] SSL connection timeout
Last error traceback:
    get_routes(od = od_school %>% slice_max(n = parameters$max_to_route,    ...
    cyclestreets::batch(desire_lines = od, wait = TRUE, maxDistance = 30000,...
    batch_jobdata(username = username, password = password, id = as.characte...
    httr::POST(url = batch_url, body = body)
    request_perform(req, hu$handle$handle)
    request_fetch(req$output, req$url, handle)
    request_fetch.write_memory(req$output, req$url, handle)
    curl::curl_fetch_memory(url, handle = handle)
    .handleSimpleError(function (condition)  {     state$error <- build_mess...
    h(simpleError(msg, call))
