### ISSUE TITLE
Understand the methodology 

### ISSUE THREAD

**Issue by Jimmy-Rail** [nptscot/npt#45]
reproduce the result of Chapter 13: 
https://geocompr.robinlovelace.net/transport.html

**Comment by mem48** [comment]
Some useful tips for getting started with R

Free course for the absolute basics https://www.datacamp.com/courses/free-introduction-to-r

R for data science free book https://r4ds.had.co.nz/ and https://www.tidyverse.org/learn/

Geocompuation with R https://geocompr.robinlovelace.net/index.html focuses on the geospatial work

The Transport Data Science Module https://github.com/ITSLeeds/TDS bit of a mess but have a look at the `.md` files in the practicals folder.

The PCT package which uses the data/methods from www.pct.bike https://itsleeds.github.io/pct/ 

Also `?function` to get the inbuilt help e.g. `?sum` or `?dplyr::slice`
