### ISSUE TITLE
Intergrate prep_for_tileing into main workflow

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#49]
FYI @Robinlovelace this is the code I used to build the current datasets.

https://github.com/nptscot/npt/blob/main/code/prep_for_tileing.R 

I suggest that the end of the pipeline should be 3 Rds files

1) A single rnet with all scenarios/routes combined. (See the code on how to combine)
2) A Zones dataset with boundaries and limited data based on  https://github.com/nptscot/npt/blob/main/R/zone_stats.R
3) Another zones dataset without boundaries and any additional data to be graphed. This will be run though `export_zone_json`

I've suggest outputs as `Rds` are preferable to `GeoJSON` & `JSON` as much smaller file sizes.  And gives good compartmentalisation between the data analysis and website-building workflows. If you want an option flag of `build_geojson` could be added.

**Comment by Robinlovelace** [comment]
Let's give this a go at 3pm.

**Comment by Robinlovelace** [comment]
Done in https://github.com/nptscot/npt/commit/8a1db35415126d3d461af3f5b22235c42c995dd4
