### ISSUE TITLE
Update pmtiles on Azure

### ISSUE THREAD

**Issue by mvl22** [nptscot/npt#491]
- [ ] Traffic count dataset
- [ ] `dasymetric{date}.pmtiles`
- [ ] Other pmtiles? We should list them

Traffic counts are coming out as numbers like:

1455.165

It does not really make sense to state 0.165 of a vehicle. I suggest rounding these, to keep the display simple.

![Screenshot 2024-05-26 at 20 44 37](https://github.com/nptscot/npt/assets/361423/092d2c21-995a-4d04-925c-2363d2d98778)

**Comment by Robinlovelace** [comment]
Cc @juanfonsecaLS1

**Comment by juanfonsecaLS1** [comment]
Just added a new release with estimates rounded to the nearest 10 https://github.com/nptscot/scottraffic/releases/tag/v5

**Comment by Robinlovelace** [comment]
Great job, thanks Juan. We just need to rebuild the pmtiles for this now I think, can you give that a go @wangzhao0217 ?

**Comment by Robinlovelace** [comment]
Next step on this: re-generate pmtiles and upload them to [v2024-05-23](https://github.com/nptscot/outputdata/releases/tag/v2024-05-23).

**Comment by wangzhao0217** [comment]
The 2024-05-23 build data is released [v2024-05-23](https://github.com/nptscot/outputdata/releases/tag/v2024-05-23)..

**Comment by wangzhao0217** [comment]
The 2024-05-23 build data is released [v2024-05-23](https://github.com/nptscot/outputdata/releases/tag/v2024-05-23).

**Comment by Robinlovelace** [comment]
:+1: great job Zhao.
