### ISSUE TITLE
Data input structure for repoducibility

### ISSUE THREAD

**Issue by temospena** [nptscot/npt#5]
Hi all,

I was thinking that a good thing to have would be a list of the input data needed with its structure (such as variables names, types, etc), so everything could be more reproducible in other projects/contexts.

I think this is even more relevant if targets are being used.

So my suggestion is to have a md or something showing the structure and a head of each input data, and maybe also in which R scripts it is used.

**Comment by Robinlovelace** [comment]
Agreed, this makes sense :+1:
