### ISSUE TITLE
Add off road cycleways to Coherent network

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#502]
Thoughts on how to do this:

- [ ] Run the code here for Edinburgh to get the off road cycleways: https://github.com/nptscot/osmactive?tab=readme-ov-file#edinburgh-example

The result should look like this:

![image](https://github.com/nptscot/npt/assets/1825120/91a6ae7c-9534-47b3-87e0-fe2f97dcfb45)

- [ ] Filter the object to keep only the separated cycleways
- [ ] Check the results and do any additional filters/additions to the object
- [ ] Add the separated cycleways to the coherent network (this may be the tricky bit)

**Comment by wangzhao0217** [comment]
cycle_network = function(area, length_threshold = 100) {
  osm = osmactive::get_travel_network("Scotland", boundary = area, boundary_type = "clipsrc")
  cycle_net = osmactive::get_cycling_network(osm)
  drive_net = osmactive::get_driving_network_major(osm)
  cycle_net = osmactive::distance_to_road(cycle_net, drive_net)
  cycle_net = osmactive::classify_cycle_infrastructure(cycle_net)
  # filter cycle_net based on column bicycle is yes dismount adn designated
  cycle_net = cycle_net |>
    filter(bicycle == "yes" | bicycle == "dismount" | bicycle == "designated") # |> select(geometry)
  cycle_net = cycle_net |>
    mutate(length = as.numeric(sf::st_length(geometry)))
  cycle_net_f = cycle_net |> filter(length > length_threshold)
  return(cycle_net_f)
}

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by Robinlovelace** [comment]
How does 

```
  cycle_net = cycle_net |>
    filter(bicycle == "yes" | bicycle == "dismount" | bicycle == "designated") # |> select(geometry)
```

Differ from 

```
  cycle_net = cycle_net |>
    filter(`Infrastructure type` == "Separated cycle track")
```

?

**Comment by wangzhao0217** [comment]
cycle_net = cycle_net |>
    filter(bicycle == "yes" | bicycle == "dismount" | bicycle == "designated")
![image](https://github.com/nptscot/npt/assets/74598734/fb29e786-c058-413d-a041-f4650ab26eb4)

cycle_net = cycle_net |> filter(cycle_segregation == "Separated cycle track") 
![image](https://github.com/nptscot/npt/assets/74598734/cb0a9581-58b9-469f-8238-050ea310a745)

cycle_net_f = cycle_net |> filter(length > length_threshold = 300)
![image](https://github.com/nptscot/npt/assets/74598734/af25522d-6a93-4b01-99aa-2685c8820ae8)

**Comment by wangzhao0217** [comment]
![image](https://github.com/nptscot/npt/assets/74598734/12a30d92-16b1-47da-8249-4dc33ddf0525)

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by Robinlovelace** [comment]
My take: 

> should we include the majority of these off-road cycleways (in blue)? Zhao has related questions in emails, sorry for all the volume of comms on this but feedback v. appreciated.

We should find a way to keep only the most important (those with continuous length above a threshold and with high potential) and simply add them onto the layer. Won't be perfect and may lead to some dangling edges but Zhao and I struggling. Food for thought in preparation for face-to-face meeting on Thursday I guess, we're close to diminishing returns in whack-a-mole but getting there.

**Comment by Robinlovelace** [comment]
A more difficult approach: add parts of the OSM network *that do not overlap with the OpenRoads dataset* to the OpenRoads dataset as a pre-processing step. That would involve connecting the dangling and disconnected edges in OSM network with the nearest point (maybe nearest point in right direction) in the OpenRoads dataset before running the corenet method so the routing works.

**Comment by Robinlovelace** [comment]
I would go with Plan A first and see how it looks after removing the isolated cycleways.

**Comment by Robinlovelace** [comment]
Any update on this @wangzhao0217 ? I guess we can update the pmtiles after your changes.

**Comment by Robinlovelace** [comment]
Progress on this: many of the off road cycleways are in there, but not connected, e.g.: 

![image](https://github.com/user-attachments/assets/62d67f3c-49ac-41cc-90e0-1bef6a54079d)

See https://nptscot.github.io/#/clos,coherentnetwork/#13.66/55.92349/-3.1323

Thoughts on how to 'join up' the network below...

**Comment by Robinlovelace** [comment]
Follow-up in conversation with @wangzhao0217 now.

Priority for this:

- [ ] Layer without overlaps (and just the Go Dutch Fastest value for now, no groups, we can always add them later)
- [ ] Explore joining disconnected off-road routes, see below ideas with steps on that

![image](https://github.com/user-attachments/assets/57388a6b-c23e-4e45-b9fc-8b7bb7c92f6b)


Source: https://www.tldraw.com/r/hoNxfsRTMB7W4rU2-O51v?v=0,-102,1920,947&p=page

**Comment by Robinlovelace** [comment]
Latest from @wangzhao0217 below, looking good:

![image](https://github.com/user-attachments/assets/7af139bd-ad75-46de-9792-ba90c7dcca78)

**Comment by Robinlovelace** [comment]
Heads-up @wangzhao0217 after converting to sfnetworks object, `degree()` should find those nodes, right? https://igraph.org/r/doc/degree.html

**Comment by Robinlovelace** [comment]
From conversation with @wangzhao0217 today:

![image](https://github.com/user-attachments/assets/0488b2ca-cf73-48c3-8eec-e2c133a63810)

Idea: add the off road paths earlier in the process so it's a pre-processing, not post-processing step.

**Comment by Robinlovelace** [comment]
This is done now, right @wangzhao0217 ? Another idea I'd like to discuss: classifying the cn by primary, secondary, etc.
