### ISSUE TITLE
Thunderforest API key

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#51]
Key needed for this project, currently using mine. Needed for OpenCycleMap

**Comment by Robinlovelace** [comment]
Closing for now, let us know if there's any action needed on this @mem48

**Comment by mem48** [comment]
This is not fixed

**Comment by Robinlovelace** [comment]
How do we get one? Cc @mvl22.

**Comment by mvl22** [comment]
> How do we get one?

Sign up on their website, here:

https://www.thunderforest.com/pricing/

**Comment by mvl22** [comment]
Any progress on this?

Perhaps in the meanwhile move this ticket over to the website repo.

**Comment by Robinlovelace** [comment]
Have signed up for a key so closing here and have emailed you @mvl22. Feel free to open a new issue to get the key into use but equally feel free to simply add the key.

**Comment by mvl22** [comment]
Now updated; thanks.
