### ISSUE TITLE
Windows changing line breaks

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#510]
For some reason Windows has changed the line breaks of every file in the repo. Any ideas how to fix @wangzhao0217 ?

For now will just do

```
git checkout .
```

And continue...

![image](https://github.com/nptscot/npt/assets/1825120/033a171f-09aa-4610-9004-08cfffb17479)

**Comment by wangzhao0217** [comment]
This is a common issue when working in a cross-platform environment. The ^M characters you see in the diff indicate that the files have Windows-style line endings (CRLF) instead of Unix-style (LF).

1. Add a .gitattributes file and add the following content:
```
* text=auto
```
2. run the following commands:
```bash
# Remove all files from the index
git rm --cached -r .

# Resets the index without changing any files
git reset --hard

# Add all files back and normalize line endings
git add --renormalize .

# Commit the changes
git commit -m "Normalize line endings"
```

**Comment by Robinlovelace** [comment]
This is great Zhao, many thanks for the tip! Let's add that to our repos.
