### ISSUE TITLE
Reduce max size of tiles in tippecanoe code

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#546]
As outlined here: https://github.com/nptscot/nptscot.github.io/issues/258

I think it's as simple as editing lines of code like this: 

https://github.com/nptscot/npt/blob/5d04e23aa14eaa9e16818a9074a68eed25adbe20/code/build.R#L246

In that case we could change it to:

```diff
-     "--maximum-tile-bytes=5000000",
+    "--maximum-tile-bytes=2000000",
```

See https://github.com/felt/tippecanoe/issues/288 and cc @mem48 who may tell us this is a terrible idea or have some other thoughts.

**Comment by mem48** [comment]
It will have to be tuned to each dataset to trade off visual fidelity and load times. There is no right answer. 

The best solution is to be brutal and drop it to the default 500K and then adjust the input geojson to archive the best visual results within the performance budget.

**Comment by Robinlovelace** [comment]
We're not going for the best solution at present, we're just looking to get it working a bit better at low zoom levels, so I suggest forging ahead with the minimal changes suggested above rather than fiddling with per dataset configs.

**Comment by wangzhao0217** [comment]
Done https://github.com/nptscot/npt/commit/3b4284fec86407c760ee1d7ceb963866b68d0eed
