### ISSUE TITLE
UI feedback from Jin

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#56]
Please take a look at the nptscot.github.io/web site and let us know anything that's not perfect @Jimmy-Rail.

**Comment by Jimmy-Rail** [comment]
Hi all
It appears that this website is presently experiencing technical difficulties (or undergoing maintenance). I am no longer able to browse the site, and refreshing the page does not resolve the issue.
See the screen shot below. 
<img width="957" alt="search" src="https://user-images.githubusercontent.com/58268501/221972202-04e8485e-b3c5-44d3-ae85-e0a19ac10e2c.PNG">

**Comment by Jimmy-Rail** [comment]
> Hi all It appears that this website is presently experiencing technical difficulties (or undergoing maintenance). I am no longer able to browse the site (the map layer and its details are missing), and refreshing the page does not resolve the issue. See the screen shot below. <img alt="search" width="957" src="https://user-images.githubusercontent.com/58268501/221972202-04e8485e-b3c5-44d3-ae85-e0a19ac10e2c.PNG">

It is now resolved.

**Comment by Robinlovelace** [comment]
Great stuff, thanks for the feedback @Jimmy-Rail ! Do you have any other comments? If you're happy with the UI for MVP please do close this issue, allowing focus on the other issue #45 .

**Comment by Jimmy-Rail** [comment]
> Great stuff, thanks for the feedback @Jimmy-Rail ! Do you have any other comments? If you're happy with the UI for MVP please do close this issue, allowing focus on the other issue #45 .

I am writing the comments, will put them here soon.

**Comment by Robinlovelace** [comment]
Great feedback. Will defer to Malcolm for responses and any low hanging fruit actions.
