### ISSUE TITLE
UI tweaks following workshop

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#60]
- [x] Move basemap selection options to bottom
- [ ] Remove "Purpose" dropdown for fast track layer launch
- [x] Replace "Line width" with "Cycling level" and remove quietness and hilliness options from the menu
- [x] Remove level of cycling options from Line colour dropdown
- [x] Move Cycling level dropdown above route type dropdown: users should be drawn to changing the scenarios first
- [x] Make the Route Network section in menu uncollapsed by default: minimise number of clicks needed to change network results

Current view below. We can add screenshots showing updated UI after these tweaks.

![image](https://user-images.githubusercontent.com/1825120/223741551-04aa73d4-8b97-4734-84bd-82a66cbd76cf.png)

**Comment by Robinlovelace** [comment]
Plan: done by end of next week.

**Comment by mem48** [comment]
Done or moved to individual issues

**Comment by Robinlovelace** [comment]
:tada:
