### ISSUE TITLE
Convert flows to AADT

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#63]
Annual Average Daily Flow is more comparible across trip types.

- [ ] Account for fact that routing is uni-directional, meaning we need to double values for AADT
- [ ] Weighting for average trips per day (see NTS), we'll need to multiply by a value representing the number of trips for different purposes made per year, was ~220 for commuting, probably less, e.g. ~150 now?

Also include estimate of peak flows. Nice to have as peaks define cyclway widths.

To do this there are many steps, including

- [x] #327

**Comment by Robinlovelace** [comment]
This is perfect for @juanfosecals1

**Comment by juanfonsecaLS1** [comment]
I have included some calculation of AADT factors using the Scottish Household Survey in the nptscot/TT_-Scottish_Household_Survey@2869f2ac845924bf51f3d5262c3f7579f362bdfa. Could you please double check the calculations?

**Comment by Robinlovelace** [comment]
Thanks @juanfonsecaLS1 currently in a meeting on the project and next steps, will plan to take a look next week, maybe Thursday. @mem48 if you get a chance could you have a look before then?

**Comment by mem48** [comment]
@juanfonsecaLS1 and @Robinlovelace where are we with this? Getting very urgent for UI work

**Comment by Robinlovelace** [comment]
> @juanfonsecaLS1 and @Robinlovelace where are we with this? Getting very urgent for UI work

@joeytalbot set up a meeting with Juan but it's postponed. I don't think it's a lot of work, will look to discuss and maybe fix it today.

**Comment by juanfonsecaLS1** [comment]
We will have a meeting with @joeytalbot on Friday to discuss this.

**Comment by Robinlovelace** [comment]
Re-opening because we now need to run the code and update the results @mem48
