### ISSUE TITLE
Combine flows of muliple paralel routes 

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#64]
https://nptscot.github.io/web/#18.21/55.951423/-3.199715

**Comment by Robinlovelace** [comment]
Looking at docs on this, it says:

> -Eattribute:operation or --accumulate-attribute=attribute:operation: Preserve the named attribute from features that are dropped, coalesced-as-needed, or clustered. The operation may be sum, product, mean, max, min, concat, or comma to specify how the named attribute is accumulated onto the attribute of the same name in a feature that does survive.

Source: https://github.com/felt/tippecanoe#modifying-feature-attributes

**Comment by Robinlovelace** [comment]
This is not a high priority and worth understanding build process and generating route network first... We have .geojson files representing theses datasets to test. Please describe your suggest approach @wangzhao0217 .

**Comment by wangzhao0217** [comment]
Here is an example code.

```python
import pandas as pd
#code

```

**Comment by wangzhao0217** [comment]
Potential way to combine multiple parallel routes, use Irish dual carriageway as an example:
1. identify the parallel routes using directed_hausdorff
2. generate centreline using Voronoi
```python
import geopandas as gpd
from shapely import wkt
import pandas as pd

data = pd.read_csv('https://github.com/wangzhao0217/data/blob/main/two%20lines.csv')

# Convert WKT strings to geometry objects
data['geometry'] = data['WKT'].apply(wkt.loads)

# Convert DataFrame to GeoDataFrame
gdf = gpd.GeoDataFrame(data, geometry='geometry')

# Set the CRS to EPSG:2157
gdf.set_crs(epsg=2157, inplace=True)
#code
# Display the first few rows
gdf.head()
gdf.plot()

**Comment by Robinlovelace** [comment]
Sounds good @wangzhao0217. Suggested next step on this: create a minimal example dataset that has known dual carriageways as a basis for testing implementations that will fix this issue. I like your thinking on this. Great progress on day 1!

**Comment by mem48** [comment]
A few links that may be useful from the ESRI world

https://pro.arcgis.com/en/pro-app/2.9/tool-reference/cartography/merge-divided-roads.htm

https://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/integrate.htm

**Comment by Robinlovelace** [comment]
If you want to add some reproducible code demonstrating/testing solutions please add here, in which ever language you see fit, but in a PR not directly to `main` @wangzhao0217: https://github.com/nptscot/npt/tree/main/code/tests

Note: you can start a 'dev branch' associated with this issue by executing the following command:

```bash
gh issue develop 64 --checkout
```

**Comment by Robinlovelace** [comment]
Latest on this: https://github.com/nptscot/networkmerge/issues/54

Progress: https://rpubs.com/RobinLovelace/1072120

**Comment by Robinlovelace** [comment]
Next step is to progress on the small example, work in progress on that, when we've got a solution for https://github.com/nptscot/networkmerge/issues/54 we can try to see how fast/slow the function is on a bigger network, and with more columns.

**Comment by Robinlovelace** [comment]
Resulting network: https://github.com/nptscot/npt/releases/download/rnet_3km_buffer/rnet_3km_buffer.geojson

![image](https://github.com/nptscot/npt/assets/1825120/d8857c6a-1c30-400a-93bc-e730378fa6f4)

**Comment by Robinlovelace** [comment]
@wangzhao0217 how did your experiment go?

**Comment by wangzhao0217** [comment]
> @wangzhao0217 how did your experiment go?

Hi Robin,
I'm sorry, can you please clarify if you were asking about the 3km trials or to identify a parallel route?
- For 3km trials, encountered errors related to multiple columns. Currently diagnosing which function is causing the issue.
- identify a parallel route, I am adding a filter based on street name, will push soon after the test

**Comment by Robinlovelace** [comment]
Is this working for the 3km buffer now? Looking forward to testing results!
