### ISSUE TITLE
Integrate network pre-processing and tiling prep code into workflow autmation pipeline

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/npt#81]
As discussed with @mem48, this may be best done in collaboration so assigning both of us.

- [ ] Create .geojsons: R/make_geojsons.R
- [ ] Tippecannoe into pmtiles: https://github.com/nptscot/npt/blob/main/tippecanoe
- [ ] Upload new version of tiles to GH
- [x] Manual: upload to Azure
- [x] Change url on dev version

**Comment by Robinlovelace** [comment]
This is not yet complete.

**Comment by mem48** [comment]
This is done?

**Comment by Robinlovelace** [comment]
Yes, the code generates the tiles.
